name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Install dependencies
      run: docker-compose run --rm redmine bundle install --jobs 4 --retry 3
    - name: Run Test
      run: docker-compose run --rm redmine bash -c "RAILS_ENV=test bin/rails db:migrate && bin/rails test"
