name: Docker Image CI

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest

    strategy:
      matrix:
        DB: [mysql, postgres]
 
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Build a redmine image
      run: docker-compose build redmine
      env: { db: ${{ matrix.DB }} }
    - name: Install dependencies
      run: docker-compose run --rm redmine bundle install --jobs 4 --retry 3
      env: { db: ${{ matrix.DB }} }
    - name: Run migrations
      run: docker-compose run --rm redmine bin/rails db:migrate RAILS_ENV=test
      env: { db: ${{ matrix.DB }} }
    - name: Prepare test repositories
      run: docker-compose run --rm redmine bin/rails test:scm:setup:all
      env: { db: ${{ matrix.DB }} }
    - name: Run test
      run: docker-compose run --rm redmine bin/rails test
      env: { db: ${{ matrix.DB }} }
    - name: Run test:system
      run: docker-compose run --rm redmine bin/rails test:system
      env: { db: ${{ matrix.DB }} }
